package modele;

public enum Country {
    USA("Etats-Unis d'Amérique", "us"),
    AFGHANISTAN("Afghanistan", "af"),
    ALBANIE("Albanie", "al"),
    ALGERIE("Algérie", "dz"),
    ANDORRE("Andorre", "ad"),
    ANGOLA("Angola", "ao"),
    ANTIGUA_DEPS("Antigua-et-Barbuda", "ag"),
    ARGENTINE("Argentine", "ar"),
    ARMENIE("Arménie", "am"),
    AUSTRALIE("Australie", "au"),
    AUTRICHE("Autriche", "at"),
    AZERBAIDJAN("Azerbaïdjan", "az"),
    BAHAMAS("Bahamas", "bs"),
    BAHREIN("Bahreïn", "bh"),
    BANGLADESH("Bangladesh", "bd"),
    BARBADE("Barbade", "bb"),
    BIELORUSSIE("Biélorussie", "by"),
    BELGIQUE("Belgique", "be"),
    BELIZE("Belize", "bz"),
    BENIN("Bénin", "bj"),
    BHOUTAN("Bhoutan", "bt"),
    BOLIVIE("Bolivie", "bo"),
    BOSNIE_HERZEGOVINE("Bosnie-Herzégovine", "ba"),
    BOTSWANA("Botswana", "bw"),
    BRESIL("Brésil", "br"),
    BRUNEI("Brunéi", "bn"),
    BULGARIE("Bulgarie", "bg"),
    BURKINA("Burkina Faso", "bf"),
    BIRMANIE("Birmanie", "mm"),
    BURUNDI("Burundi", "bi"),
    CAMBODGE("Cambodge", "kh"),
    CAMEROUN("Cameroun", "cm"),
    CANADA("Canada", "ca"),
    CAP_VERT("Cap-Vert", "cv"),
    REPUBLIQUE_CENTRAFRICAINE("République centrafricaine", "cf"),
    TCHAD("Tchad", "td"),
    CHILI("Chili", "cl"),
    CHINE("Chine", "cn"),
    COLOMBIE("Colombie", "co"),
    COMORES("Comores", "km"),
    REPUBLIQUE_DEMOCRATIQUE_DU_CONGO("République démocratique du Congo", "cd"),
    REPUBLIQUE_DU_CONGO("République du Congo", "cg"),
    COSTA_RICA("Costa Rica", "cr"),
    CROATIE("Croatie", "hr"),
    CUBA("Cuba", "cu"),
    CHYPRE("Chypre", "cy"),
    REPUBLIQUE_TCHEQUE("République tchèque", "cz"),
    DANZIG("Danzig", "dz"),
    DANEMARK("Danemark", "dk"),
    DJIBOUTI("Djibouti", "dj"),
    DOMINIQUE("Dominique", "dm"),
    REPUBLIQUE_DOMINICAINE("République dominicaine", "do"),
    TIMOR_ORIENTAL("Timor oriental", "tl"),
    EQUATEUR("Équateur", "ec"),
    EGYPTE("Égypte", "eg"),
    SALVADOR("Salvador", "sv"),
    GUINEE_EQUATORIALE("Guinée équatoriale", "gq"),
    ERYTHREE("Érythrée", "er"),
    ESTONIE("Estonie", "ee"),
    ETHIOPIE("Éthiopie", "et"),
    FIDJI("Fidji", "fj"),
    FINLANDE("Finlande", "fi"),
    FRANCE("France", "fr"),
    GABON("Gabon", "ga"),
    BANDE_DE_GAZA("Bande de Gaza", "ps"),
    GAMBIE("Gambie", "gm"),
    GEORGIE("Géorgie", "ge"),
    ALLEMAGNE("Allemagne", "de"),
    GHANA("Ghana", "gh"),
    GRECE("Grèce", "gr"),
    GRENADE("Grenade", "gd"),
    GUATEMALA("Guatemala", "gt"),
    GUINEE("Guinée", "gn"),
    GUINEE_BISSAU("Guinée-Bissau", "gw"),
    GUYANA("Guyana", "gy"),
    HAITI("Haïti", "ht"),
    SAINT_SIEGE("Saint-Siège", "va"),
    HONDURAS("Honduras", "hn"),
    HONGRIE("Hongrie", "hu"),
    ISLANDE("Islande", "is"),
    INDE("Inde", "in"),
    INDONESIE("Indonésie", "id"),
    IRAN("Iran", "ir"),
    IRAQ("Irak", "iq"),
    IRLANDE("Irlande", "ie"),
    ISRAEL("Israël", "il"),
    ITALIE("Italie", "it"),
    COTE_D_IVOIRE("Côte d'Ivoire", "ci"),
    JAMAIQUE("Jamaïque", "jm"),
    JAPON("Japon", "jp"),
    JONATHANLAND("Jonathanland", "jl"),
    JORDANIE("Jordanie", "jo"),
    KAZAKHSTAN("Kazakhstan", "kz"),
    KENYA("Kenya", "ke"),
    KIRIBATI("Kiribati", "ki"),
    COREE_DU_NORD("Corée du Nord", "kp"),
    COREE_DU_SUD("Corée du Sud", "kr"),
    KOSOVO("Kosovo", "xk"),
    KOWEIT("Koweït", "kw"),
    KIRGHIZISTAN("Kirghizistan", "kg"),
    LAOS("Laos", "la"),
    LETTONIE("Lettonie", "lv"),
    LIBAN("Liban", "lb"),
    LESOTHO("Lesotho", "ls"),
    LIBERIA("Libéria", "lr"),
    LIBYE("Libye", "ly"),
    LIECHTENSTEIN("Liechtenstein", "li"),
    LITUANIE("Lituanie", "lt"),
    LUXEMBOURG("Luxembourg", "lu"),
    MACEDOINE("Macédoine", "mk"),
    MADAGASCAR("Madagascar", "mg"),
    MALAWI("Malawi", "mw"),
    MALAISIE("Malaisie", "my"),
    MALDIVES("Maldives", "mv"),
    MALI("Mali", "ml"),
    MALTE("Malte", "mt"),
    ILES_MARSHALL("Îles Marshall", "mh"),
    MAURITANIE("Mauritanie", "mr"),
    MAURICE("Maurice", "mu"),
    MEXIQUE("Mexique", "mx"),
    ETATS_FEDERES_DE_MICRONESIE("États fédérés de Micronésie", "fm"),
    MOLDAVIE("Moldavie", "md"),
    MONACO("Monaco", "mc"),
    MONGOLIE("Mongolie", "mn"),
    MONTENEGRO("Monténégro", "me"),
    MAROC("Maroc", "ma"),
    MOZAMBIQUE("Mozambique", "mz"),
    NAMIBIE("Namibie", "na"),
    NAURU("Nauru", "nr"),
    NEPAL("Népal", "np"),
    PAYS_BAS("Pays-Bas", "nl"),
    NOUVELLE_ZELANDE("Nouvelle-Zélande", "nz"),
    NICARAGUA("Nicaragua", "ni"),
    NIGER("Niger", "ne"),
    NIGERIA("Nigeria", "ng"),
    NORVEGE("Norvège", "no"),
    OMAN("Oman", "om"),
    PAKISTAN("Pakistan", "pk"),
    PALAOS("Palaos", "pw"),
    PALESTINE("Palestine", "ps"),
    PANAMA("Panama", "pa"),
    PAPUA_NOUVELLE_GUINEE("Papouasie-Nouvelle-Guinée", "pg"),
    PARAGUAY("Paraguay", "py"),
    PEROU("Pérou", "pe"),
    PHILIPPINES("Philippines", "ph"),
    POLOGNE("Pologne", "pl"),
    PORTUGAL("Portugal", "pt"),
    QATAR("Qatar", "qa"),
    ROUMANIE("Roumanie", "ro"),
    RUSSIE("Russie", "ru"),
    RWANDA("Rwanda", "rw"),
    SAINT_KITTS_ET_NEVIS("Saint-Kitts-et-Nevis", "kn"),
    SAINTE_LUCIE("Sainte-Lucie", "lc"),
    SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines", "vc"),
    SAMOA("Samoa", "ws"),
    SAINT_MARIN("Saint-Marin", "sm"),
    SAO_TOME_ET_PRINCIPE("Sao Tomé-et-Principe", "st"),
    ARABIE_SAOUDITE("Arabie saoudite", "sa"),
    SENEGAL("Sénégal", "sn"),
    SERBIE("Serbie", "rs"),
    SEYCHELLES("Seychelles", "sc"),
    SIERRA_LEONE("Sierra Leone", "sl"),
    SINGAPOUR("Singapour", "sg"),
    SLOVAQUIE("Slovaquie", "sk"),
    SLOVENIE("Slovénie", "si"),
    ILES_SOLOMON("Îles Salomon", "sb"),
    SOMALIE("Somalie", "so"),
    AFRIQUE_DU_SUD("Afrique du Sud", "za"),
    SUD_SOUDAN("Soudan du Sud", "ss"),
    ESPAGNE("Espagne", "es"),
    SRI_LANKA("Sri Lanka", "lk"),
    SOUDAN("Soudan", "sd"),
    SURINAME("Suriname", "sr"),
    SWAZILAND("Swaziland", "sz"),
    SUEDE("Suède", "se"),
    SUISSE("Suisse", "ch"),
    SYRIE("Syrie", "sy"),
    TAIWAN("Taïwan", "tw"),
    TADJIKISTAN("Tadjikistan", "tj"),
    TANZANIE("Tanzanie", "tz"),
    THAILANDE("Thaïlande", "th"),
    TOGO("Togo", "tg"),
    TONGA("Tonga", "to"),
    TRINITE_ET_TOBAGO("Trinité-et-Tobago", "tt"),
    TUNISIE("Tunisie", "tn"),
    TURQUIE("Turquie", "tr"),
    TURKMENISTAN("Turkménistan", "tm"),
    TUVALU("Tuvalu", "tv"),
    OUGANDA("Ouganda", "ug"),
    UKRAINE("Ukraine", "ua"),
    EMIRATS_ARABES_UNIS("Émirats arabes unis", "ae"),
    ROYAUME_UNI("Royaume-Uni", "gb"),
    URUGUAY("Uruguay", "uy"),
    OUZBEKISTAN("Ouzbékistan", "uz"),
    VANUATU("Vanuatu", "vu"),
    VENEZUELA("Venezuela", "ve"),
    VIETNAM("Viêt Nam", "vn"),
    YEMEN("Yémen", "ye"),
    ZAMBIE("Zambie", "zm"),
    ZIMBABWE("Zimbabwe", "zw");

    private String nom;
    private String code;
    
    private Country(String nom, String code) {
        this.nom = nom;
        this.code = code;
    }
    
    public String getNom() {
        return nom;
    }
    
    public String getCode() {
        return code;
    }
}