package modele;

public enum Country {
    USA("United States of America", "us"),
    AFGHANISTAN("Afghanistan", "af"),
    ALBANIA("Albania", "al"),
    ALGERIA("Algeria", "dz"),
    ANDORRA("Andorra", "ad"),
    ANGOLA("Angola", "ao"),
    ANTIGUA_DEPS("Antigua & Deps", "ag"),
    ARGENTINA("Argentina", "ar"),
    ARMENIA("Armenia", "am"),
    AUSTRALIA("Australia", "au"),
    AUSTRIA("Austria", "at"),
    AZERBAIJAN("Azerbaijan", "az"),
    BAHAMAS("Bahamas", "bs"),
    BAHRAIN("Bahrain", "bh"),
    BANGLADESH("Bangladesh", "bd"),
    BARBADOS("Barbados", "bb"),
    BELARUS("Belarus", "by"),
    BELGIUM("Belgium", "be"),
    BELIZE("Belize", "bz"),
    BENIN("Benin", "bj"),
    BHUTAN("Bhutan", "bt"),
    BOLIVIA("Bolivia", "bo"),
    BOSNIA_HERZEGOVINA("Bosnia Herzegovina", "ba"),
    BOTSWANA("Botswana", "bw"),
    BRAZIL("Brazil", "br"),
    BRUNEI("Brunei", "bn"),
    BULGARIA("Bulgaria", "bg"),
    BURKINA("Burkina", "bf"),
    BURMA("Burma", "mm"),
    BURUNDI("Burundi", "bi"),
    CAMBODIA("Cambodia", "kh"),
    CAMEROON("Cameroon", "cm"),
    CANADA("Canada", "ca"),
    CAPE_VERDE("Cape Verde", "cv"),
    CENTRAL_AFRICAN_REP("Central African Rep", "cf"),
    CHAD("Chad", "td"),
    CHILE("Chile", "cl"),
    CHINA("Republic of China", "cn"),
    REPUBLIC_OF_CHINA("Republic of China", "cn"),
    COLOMBIA("Colombia", "co"),
    COMOROS("Comoros", "km"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo", "cd"),
    REPUBLIC_OF_THE_CONGO("Republic of the Congo", "cg"),
    COSTA_RICA("Costa Rica", "cr"),
    CROATIA("Croatia", "hr"),
    CUBA("Cuba", "cu"),
    CYPRUS("Cyprus", "cy"),
    CZECH_REPUBLIC("Czech Republic", "cz"),
    DANZIG("Danzig", "dz"),
    DENMARK("Denmark", "dk"),
    DJIBOUTI("Djibouti", "dj"),
    DOMINICA("Dominica", "dm"),
    DOMINICAN_REPUBLIC("Dominican Republic", "do"),
    EAST_TIMOR("East Timor", "tl"),
    ECUADOR("Ecuador", "ec"),
    EGYPT("Egypt", "eg"),
    EL_SALVADOR("El Salvador", "sv"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "gq"),
    ERITREA("Eritrea", "er"),
    ESTONIA("Estonia", "ee"),
    ETHIOPIA("Ethiopia", "et"),
    FIJI("Fiji", "fj"),
    FINLAND("Finland", "fi"),
    FRANCE("France", "fr"),
    GABON("Gabon", "ga"),
    GAZA_STRIP("Gaza Strip", "ps"),
    THE_GAMBIA("The Gambia", "gm"),
    GEORGIA("Georgia", "ge"),
    GERMANY("Germany", "de"),
    GHANA("Ghana", "gh"),
    GREECE("Greece", "gr"),
    GRENADA("Grenada", "gd"),
    GUATEMALA("Guatemala", "gt"),
    GUINEA("Guinea", "gn"),
    GUINEA_BISSAU("Guinea-Bissau", "gw"),
    GUYANA("Guyana", "gy"),
    HAITI("Haiti", "ht"),
    HOLY_ROMAN_EMPIRE("Holy Roman Empire", "de"),
    HONDURAS("Honduras", "hn"),
    HUNGARY("Hungary", "hu"),
    ICELAND("Iceland", "is"),
    INDIA("India", "in"),
    INDONESIA("Indonesia", "id"),
    IRAN("Iran", "ir"),
    IRAQ("Iraq", "iq"),
    REPUBLIC_OF_IRELAND("Republic of Ireland", "ie"),
    ISRAEL("Israel", "il"),
    ITALY("Italy", "it"),
    IVORY_COAST("Ivory Coast", "ci"),
    JAMAICA("Jamaica", "jm"),
    JAPAN("Japan", "jp"),
    JONATHANLAND("Jonathanland", "jl"),
    JORDAN("Jordan", "jo"),
    KAZAKHSTAN("Kazakhstan", "kz"),
    KENYA("Kenya", "ke"),
    KIRIBATI("Kiribati", "ki"),
    NORTH_KOREA("North Korea", "kp"),
    SOUTH_KOREA("South Korea", "kr"),
    KOSOVO("Kosovo", "xk"),
    KUWAIT("Kuwait", "kw"),
    KYRGYZSTAN("Kyrgyzstan", "kg"),                                                                                                                             
    LAOS("Laos", "la"),                                                                                                                                         
    LATVIA("Latvia", "lv"),                                                                                                                                     
    LEBANON("Lebanon", "lb"),                                                                                                                                   
    LESOTHO("Lesotho", "ls"),                                                                                                                                   
    LIBERIA("Liberia", "lr"),                                                                                                                                   
    LIBYA("Libya", "ly"),                                                                                                                                       
    LIECHTENSTEIN("Liechtenstein", "li"),                                                                                                                       
    LITHUANIA("Lithuania", "lt"),                                                                                                                               
    LUXEMBOURG("Luxembourg", "lu"),                                                                                                                             
    MACEDONIA("Macedonia", "mk"),                                                                                                                               
    MADAGASCAR("Madagascar", "mg"),                                                                                                                             
    MALAWI("Malawi", "mw"),                                                                                                                                     
    MALAYSIA("Malaysia", "my"),                                                                                                                                 
    MALDIVES("Maldives", "mv"),                                                                                                                                 
    MALI("Mali", "ml"),                                                                                                                                         
    MALTA("Malta", "mt"),                                                                                                                                       
    MARSHALL_ISLANDS("Marshall Islands", "mh"),                                                                                                                 
    MAURITANIA("Mauritania", "mr"),                                                                                                                             
    MAURITIUS("Mauritius", "mu"),                                                                                                                               
    MEXICO("Mexico", "mx"),                                                                                                                                     
    MICRONESIA("Micronesia", "fm"),                                                                                                                             
    MOLDOVA("Moldova", "md"),                                                                                                                                   
    MONACO("Monaco", "mc"),                                                                                                                                     
    MONGOLIA("Mongolia", "mn"),                                                                                                                                 
    MONTENEGRO("Montenegro", "me"),                                                                                                                             
    MOROCCO("Morocco", "ma"),                                                                                                                                   
    MOUNT_ATHOS("Mount Athos", "xa"),                                                                                                                           
    MOZAMBIQUE("Mozambique", "mz"),                                                                                                                             
    NAMIBIA("Namibia", "na"),                                                                                                                                   
    NAURU("Nauru", "nr"),                                                                                                                                       
    NEPAL("Nepal", "np"),                                                                                                                                       
    NEWFOUNDLAND("Newfoundland", "nf"),                                                                                                                         
    NETHERLANDS("Netherlands", "nl"),                                                                                                                           
    NEW_ZEALAND("New Zealand", "nz"),                                                                                                                           
    NICARAGUA("Nicaragua", "ni"),                                                                                                                               
    NIGER("Niger", "ne"),                                                                                                                                       
    NIGERIA("Nigeria", "ng"),                                                                                                                                   
    NORWAY("Norway", "no"),                                                                                                                                     
    OMAN("Oman", "om"),                                                                                                                                         
    OTTOMAN_EMPIRE("Ottoman Empire", "ot"),                                                                                                                     
    PAKISTAN("Pakistan", "pk"),                                                                                                                                 
    PALAU("Palau", "pw"),                                                                                                                                       
    PANAMA("Panama", "pa"),                                                                                                                                     
    PAPUA_NEW_GUINEA("Papua New Guinea", "pg"),                                                                                                                 
    PARAGUAY("Paraguay", "py"),                                                                                                                                 
    PERU("Peru", "pe"),                                                                                                                                         
    PHILIPPINES("Philippines", "ph"),                                                                                                                           
    POLAND("Poland", "pl"),                                                                                                                                     
    PORTUGAL("Portugal", "pt"),                                                                                                                                 
    PRUSSIA("Prussia", "pr"),                                                                                                                                   
    QATAR("Qatar", "qa"),                                                                                                                                       
    ROMANIA("Romania", "ro"),                                                                                                                                   
    ROME("Rome", "rm"),                                                                                                                                         
    RUSSIAN_FEDERATION("Russian Federation", "ru"),                                                                                                             
    RWANDA("Rwanda", "rw"),                                                                                                                                     
    GRENADINES("Grenadines", "gd"),                                                                                                                             
    SAMOA("Samoa", "ws"),                                                                                                                                       
    SAN_MARINO("San Marino", "sm"),                                                                                                                             
    SAO_TOME_PRINCIPE("Sao Tome & Principe", "st"),                                                                                                             
    SAUDI_ARABIA("Saudi Arabia", "sa"),                                                                                                                         
    SENEGAL("Senegal", "sn"),                                                                                                                                   
    SERBIA("Serbia", "rs"),                                                                                                                                     
    SEYCHELLES("Seychelles", "sc"),                                                                                                                             
    SIERRA_LEONE("Sierra Leone", "sl"),                                                                                                                         
    SINGAPORE("Singapore", "sg"),                                                                                                                               
    SLOVAKIA("Slovakia", "sk"),                                                                                                                                 
    SLOVENIA("Slovenia", "si"),                                                                                                                                 
    SOLOMON_ISLANDS("Solomon Islands", "sb"),                                                                                                                   
    SOMALIA("Somalia", "so"),                                                                                                                                   
    SOUTH_AFRICA("South Africa", "za"),                                                                                                                         
    SPAIN("Spain", "es"),                                                                                                                                       
    SRI_LANKA("Sri Lanka", "lk"),                                                                                                                               
    SUDAN("Sudan", "sd"),                                                                                                                                       
    SURINAME("Suriname", "sr"),                                                                                                                                 
    SWAZILAND("Swaziland", "sz"),                                                                                                                               
    SWEDEN("Sweden", "se"),                                                                                                                                     
    SWITZERLAND("Switzerland", "ch"),                                                                                                                           
    SYRIA("Syria", "sy"),                                                                                                                                       
    TAJIKISTAN("Tajikistan", "tj"),                                                                                                                             
    TANZANIA("Tanzania", "tz"),                                                                                                                                 
    THAILAND("Thailand", "th"),                                                                                                                                 
    TOGO("Togo", "tg"),                                                                                                                                         
    TONGA("Tonga", "to"),                                                                                                                                       
    TRINIDAD_TOBAGO("Trinidad & Tobago", "tt"),                                                                                                                 
    TUNISIA("Tunisia", "tn"),                                                                                                                                   
    TURKEY("Turkey", "tr"),                                                                                                                                     
    TURKMENISTAN("Turkmenistan", "tm"),                                                                                                                         
    TUVALU("Tuvalu", "tv"),                                                                                                                                     
    UGANDA("Uganda", "ug"),                                                                                                                                     
    UKRAINE("Ukraine", "ua"),                                                                                                                                   
    UNITED_ARAB_EMIRATES("United Arab Emirates", "ae"),                                                                                                         
    UNITED_KINGDOM("United Kingdom", "gb"),
    URUGUAY("Uruguay","uy"),
    UZBEKISTAN("Uzbekistan","uy"),
    VANUATU("Vanuatu","vu"),
    VATICAN_CITY("Vatican City","uy"),
    VENEZUELA("Venezuela","ve"),
    VIETNAM("Vietnam","vn"),
    YEMEN("Yemen","ye"),
    ZAMBIA("Zambia","zm"),
    ZIMBABWE("Zimbabwe","zw");


    private String name;
    private String code;
    
    private Country(String name, String code) {
        this.name = name;
        this.code = code;
    }
    
    public String getName() {
        return name;
    }
    
    public String getCode() {
        return code;
    }

}