package modele;

public enum Country {
    USA("United States of America", "us"),
    AFGHANISTAN("Afghanistan", "af"),
    ALBANIA("Albania", "al"),
    ALGERIA("Algeria", "dz"),
    ANDORRA("Andorra", "ad"),
    ANGOLA("Angola", "ao"),
    ANTIGUA_DEPS("Antigua & Deps", "ag"),
    ARGENTINA("Argentina", "ar"),
    ARMENIA("Armenia", "am"),
    AUSTRALIA("Australia", "au"),
    AUSTRIA("Austria", "at"),
    AZERBAIJAN("Azerbaijan", "az"),
    BAHAMAS("Bahamas", "bs"),
    BAHRAIN("Bahrain", "bh"),
    BANGLADESH("Bangladesh", "bd"),
    BARBADOS("Barbados", "bb"),
    BELARUS("Belarus", "by"),
    BELGIUM("Belgium", "be"),
    BELIZE("Belize", "bz"),
    BENIN("Benin", "bj"),
    BHUTAN("Bhutan", "bt"),
    BOLIVIA("Bolivia", "bo"),
    BOSNIA_HERZEGOVINA("Bosnia Herzegovina", "ba"),
    BOTSWANA("Botswana", "bw"),
    BRAZIL("Brazil", "br"),
    BRUNEI("Brunei", "bn"),
    BULGARIA("Bulgaria", "bg"),
    BURKINA("Burkina", "bf"),
    BURMA("Burma", "mm"),
    BURUNDI("Burundi", "bi"),
    CAMBODIA("Cambodia", "kh"),
    CAMEROON("Cameroon", "cm"),
    CANADA("Canada", "ca"),
    CAPE_VERDE("Cape Verde", "cv"),
    CENTRAL_AFRICAN_REP("Central African Rep", "cf"),
    CHAD("Chad", "td"),
    CHILE("Chile", "cl"),
    CHINA("Republic of China", "cn"),
    REPUBLIC_OF_CHINA("Republic of China", "cn"),
    COLOMBIA("Colombia", "co"),
    COMOROS("Comoros", "km"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo", "cd"),
    REPUBLIC_OF_THE_CONGO("Republic of the Congo", "cg"),
    COSTA_RICA("Costa Rica", "cr"),
    CROATIA("Croatia", "hr"),
    CUBA("Cuba", "cu"),
    CYPRUS("Cyprus", "cy"),
    CZECH_REPUBLIC("Czech Republic", "cz"),
    DANZIG("Danzig", "dz"),
    DENMARK("Denmark", "dk"),
    DJIBOUTI("Djibouti", "dj"),
    DOMINICA("Dominica", "dm"),
    DOMINICAN_REPUBLIC("Dominican Republic", "do"),
    EAST_TIMOR("East Timor", "tl"),
    ECUADOR("Ecuador", "ec"),
    EGYPT("Egypt", "eg"),
    EL_SALVADOR("El Salvador", "sv"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "gq"),
    ERITREA("Eritrea", "er"),
    ESTONIA("Estonia", "ee"),
    ETHIOPIA("Ethiopia", "et"),
    FIJI("Fiji", "fj"),
    FINLAND("Finland", "fi"),
    FRANCE("France", "fr"),
    GABON("Gabon", "ga"),
    GAZA_STRIP("Gaza Strip", "ps"),
    THE_GAMBIA("The Gambia", "gm"),
    GEORGIA("Georgia", "ge"),
    GERMANY("Germany", "de"),
    GHANA("Ghana", "gh"),
    GREECE("Greece", "gr"),
    GRENADA("Grenada", "gd"),
    GUATEMALA("Guatemala", "gt"),
    GUINEA("Guinea", "gn"),
    GUINEA_BISSAU("Guinea-Bissau", "gw"),
    GUYANA("Guyana", "gy"),
    HAITI("Haiti", "ht"),
    HOLY_ROMAN_EMPIRE("Holy Roman Empire", "de"),
    HONDURAS("Honduras", "hn"),
    HUNGARY("Hungary", "hu"),
    ICELAND("Iceland", "is"),
    INDIA("India", "in"),
    INDONESIA("Indonesia", "id"),
    IRAN("Iran", "ir"),
    IRAQ("Iraq", "iq"),
    REPUBLIC_OF_IRELAND("Republic of Ireland", "ie"),
    ISRAEL("Israel", "il"),
    ITALY("Italy", "it"),
    IVORY_COAST("Ivory Coast", "ci"),
    JAMAICA("Jamaica", "jm"),
    JAPAN("Japan", "jp"),
    JONATHANLAND("Jonathanland", "jl"),
    JORDAN("Jordan", "jo"),
    KAZAKHSTAN("Kazakhstan", "kz"),
    KENYA("Kenya", "ke"),
    KIRIBATI("Kiribati", "ki"),
    NORTH_KOREA("North Korea", "kp"),
    SOUTH_KOREA("South Korea", "KR"),
    KOSOVO("Kosovo", "XK"),
    KUWAIT("Kuwait", "KW"),
    KYRGYZSTAN("Kyrgyzstan", "KG"),
    LAOS("Laos", "LA"),
    LATVIA("Latvia", "LV"),
    LEBANON("Lebanon", "LB"),
    LESOTHO("Lesotho", "LS"),
    LIBERIA("Liberia", "LR"),
    LIBYA("Libya", "LY"),
    LIECHTENSTEIN("Liechtenstein", "LI"),
    LITHUANIA("Lithuania", "LT"),
    LUXEMBOURG("Luxembourg", "LU"),
    MACEDONIA("Macedonia", "MK"),
    MADAGASCAR("Madagascar", "MG"),
    MALAWI("Malawi", "MW"),
    MALAYSIA("Malaysia", "MY"),
    MALDIVES("Maldives", "MV"),
    MALI("Mali", "ML"),
    MALTA("Malta", "MT"),
    MARSHALL_ISLANDS("Marshall Islands", "MH"),
    MAURITANIA("Mauritania", "MR"),
    MAURITIUS("Mauritius", "MU"),
    MEXICO("Mexico", "MX"),
    MICRONESIA("Micronesia", "FM"),
    MOLDOVA("Moldova", "MD"),
    MONACO("Monaco", "MC"),
    MONGOLIA("Mongolia", "MN"),
    MONTENEGRO("Montenegro", "ME"),
    MOROCCO("Morocco", "MA"),
    MOUNT_ATHOS("Mount Athos", "XA"),
    MOZAMBIQUE("Mozambique", "MZ"),
    NAMIBIA("Namibia", "NA"),
    NAURU("Nauru", "NR"),
    NEPAL("Nepal", "NP"),
    NEWFOUNDLAND("Newfoundland", "NF"),
    NETHERLANDS("Netherlands", "NL"),
    NEW_ZEALAND("New Zealand", "NZ"),
    NICARAGUA("Nicaragua", "NI"),
    NIGER("Niger", "NE"),
    NIGERIA("Nigeria", "NG"),
    NORWAY("Norway", "NO"),
    OMAN("Oman", "OM"),
    OTTOMAN_EMPIRE("Ottoman Empire", "OT"),
    PAKISTAN("Pakistan", "PK"),
    PALAU("Palau", "PW"),
    PANAMA("Panama", "PA"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG"),
    PARAGUAY("Paraguay", "PY"),
    PERU("Peru", "PE"),
    PHILIPPINES("Philippines", "PH"),
    POLAND("Poland", "PL"),
    PORTUGAL("Portugal", "PT"),
    PRUSSIA("Prussia", "PR"),
    QATAR("Qatar", "QA"),
    ROMANIA("Romania", "RO"),
    ROME("Rome", "RM"),
    RUSSIAN_FEDERATION("Russian Federation", "RU"),
    RWANDA("Rwanda", "RW"),
    GRENADINES("Grenadines", "GD"),
    SAMOA("Samoa", "WS"),
    SAN_MARINO("San Marino", "SM"),
    SAO_TOME_PRINCIPE("Sao Tome & Principe", "ST"),
    SAUDI_ARABIA("Saudi Arabia", "SA"),
    SENEGAL("Senegal", "SN"),
    SERBIA("Serbia", "RS"),
    SEYCHELLES("Seychelles", "SC"),
    SIERRA_LEONE("Sierra Leone", "SL"),
    SINGAPORE("Singapore", "SG"),
    SLOVAKIA("Slovakia", "SK"),
    SLOVENIA("Slovenia", "SI"),
    SOLOMON_ISLANDS("Solomon Islands", "SB"),
    SOMALIA("Somalia", "SO"),
    SOUTH_AFRICA("South Africa", "ZA"),
    SPAIN("Spain", "ES"),
    SRI_LANKA("Sri Lanka", "LK"),
    SUDAN("Sudan", "SD"),
    SURINAME("Suriname", "SR"),
    SWAZILAND("Swaziland", "SZ"),
    SWEDEN("Sweden", "SE"),
    SWITZERLAND("Switzerland", "CH"),
    SYRIA("Syria", "SY"),
    TAJIKISTAN("Tajikistan", "TJ"),
    TANZANIA("Tanzania", "TZ"),
    THAILAND("Thailand", "TH"),
    TOGO("Togo", "TG"),
    TONGA("Tonga", "TO"),
    TRINIDAD_TOBAGO("Trinidad & Tobago", "TT"),
    TUNISIA("Tunisia", "TN"),
    TURKEY("Turkey", "TR"),
    TURKMENISTAN("Turkmenistan", "TM"),
    TUVALU("Tuvalu", "TV"),
    UGANDA("Uganda", "UG"),
    UKRAINE("Ukraine", "UA"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE"),
    UNITED_KINGDOM("United Kingdom", "GB"),
    URUGUAY("Uruguay","uy"),
    UZBEKISTAN("Uzbekistan","uy"),
    VANUATU("Vanuatu","vu"),
    VATICAN_CITY("Vatican City","uy"),
    VENEZUELA("Venezuela","ve"),
    VIETNAM("Vietnam","vn"),
    YEMEN("Yemen","ye"),
    ZAMBIA("Zambia","zm"),
    ZIMBABWE("Zimbabwe","zw");


    private String name;
    private String code;
    
    private Country(String name, String code) {
        this.name = name;
        this.code = code;
    }
    
    public String getName() {
        return name;
    }
    
    public String getCode() {
        return code;
    }
}