package modele;

public enum Pays {
	AFGHANISTAN("Afghanistan", "af"),
	AFRIQUE_DU_SUD("Afrique du Sud", "za"),
	ALBANIE("Albanie", "al"),
	ALGERIE("Algérie", "dz"),
	ALLEMAGNE("Allemagne", "de"),
	ANDORRE("Andorre", "ad"),
	ANGOLA("Angola", "ao"),
	ANTIGUA_ET_BARBUDA("Antigua-et-Barbuda", "ag"),
	ARABIE_SAOUDITE("Arabie saoudite", "sa"),
	ARGENTINE("Argentine", "ar"),
	ARMENIE("Arménie", "am"),
	AUSTRALIE("Australie", "au"),
	AUTRICHE("Autriche", "at"),
	AZERBAIDJAN("Azerbaïdjan", "az"),
	BAHAMAS("Bahamas", "bs"),
	BAHREIN("Bahreïn", "bh"),
	BANDE_DE_GAZA("Bande de Gaza", "ps"),
	BANGLADESH("Bangladesh", "bd"),
	BARBADE("Barbade", "bb"),
	BELGIQUE("Belgique", "be"),
	BELIZE("Belize", "bz"),
	BENIN("Bénin", "bj"),
	BHOUTAN("Bhoutan", "bt"),
	BIELORUSSIE("Biélorussie", "by"),
	BIRMANIE("Birmanie", "mm"),
	BOLIVIE("Bolivie", "bo"),
	BOSNIE_HERZEGOVINE("Bosnie-Herzégovine", "ba"),
	BOTSWANA("Botswana", "bw"),
	BRESIL("Brésil", "br"),
	BRUNEI("Brunéi", "bn"),
	BULGARIE("Bulgarie", "bg"),
	BURKINA("Burkina Faso", "bf"),
	BURUNDI("Burundi", "bi"),
	CAMBODGE("Cambodge", "kh"),
	CAMEROUN("Cameroun", "cm"),
	CANADA("Canada", "ca"),
	CAP_VERT("Cap-Vert", "cv"),
	CHILI("Chili", "cl"),
	CHINE("Chine", "cn"),
	CHYPRE("Chypre", "cy"),
	COREE_DU_NORD("Corée du Nord", "kp"),
	COREE_DU_SUD("Corée du Sud", "kr"),
	COSTA_RICA("Costa Rica", "cr"),
	COTE_D_IVOIRE("Côte d'Ivoire", "ci"),
	CROATIE("Croatie", "hr"),
	CUBA("Cuba", "cu"),
	DANEMARK("Danemark", "dk"),
	DANZIG("Danzig", "dz"),
	DJIBOUTI("Djibouti", "dj"),
	DOMINIQUE("Dominique", "dm"),
	REPUBLIQUE_DOMINICAINE("République dominicaine", "do"),
	EGYPTE("Égypte", "eg"),
	EMIRATS_ARABES_UNIS("Émirats arabes unis", "ae"),
	EQUATEUR("Équateur", "ec"),
	ERYTHREE("Érythrée", "er"),
	ESPAGNE("Espagne", "es"),
	ESTONIE("Estonie", "ee"),
	ETAT_UNIS_D_AMERIQUE("Etats-Unis d'Amérique", "us"),
	ETATS_FEDERES_DE_MICRONESIE("États fédérés de Micronésie", "fm"),
	ETHIOPIE("Éthiopie", "et"),
	FINLANDE("Finlande", "fi"),
	FRANCE("France", "fr"),
	FIDJI("Fidji", "fj"),
	GABON("Gabon", "ga"),
	GAMBIE("Gambie", "gm"),
	GEORGIE("Géorgie", "ge"),
	GHANA("Ghana", "gh"),
	GRECE("Grèce", "gr"),
	GRENADE("Grenade", "gd"),
	GROENLAND("Groenland", "gl"),
	GUATEMALA("Guatemala", "gt"),
	GUINEE("Guinée", "gn"),
	GUINEE_BISSAU("Guinée-Bissau", "gw"),
	GUINEE_EQUATORIALE("Guinée équatoriale", "gq"),
	GUYANA("Guyana", "gy"),
	HAITI("Haïti", "ht"),
	HONDURAS("Honduras", "hn"),
	HONGRIE("Hongrie", "hu"),
	ILES_SOLOMON("Îles Salomon", "sb"),
	ILES_MARSHALL("Îles Marshall", "mh"),
	INDE("Inde", "in"),
	INDONESIE("Indonésie", "id"),
	IRAN("Iran", "ir"),
	IRAK("Irak", "iq"),
	IRLANDE("Irlande", "ie"),
	ISLANDE("Islande", "is"),
	ISRAEL("Israël", "il"),
	ITALIE("Italie", "it"),
	JAMAIQUE("Jamaïque", "jm"),
	JAPON("Japon", "jp"),
	JONATHANLAND("Jonathanland", "jl"),
	JORDANIE("Jordanie", "jo"),
	KAZAKHSTAN("Kazakhstan", "kz"),
	KENYA("Kenya", "ke"),
	KIRGHIZISTAN("Kirghizistan", "kg"),
	KIRIBATI("Kiribati", "ki"),
	KOSOVO("Kosovo", "xk"),
	KOWEIT("Koweït", "kw"),
	LAOS("Laos", "la"),
	LESOTHO("Lesotho", "ls"),
	LETTONIE("Lettonie", "lv"),
	LIBAN("Liban", "lb"),
	LIBERIA("Libéria", "lr"),
	LIBYE("Libye", "ly"),
	LIECHTENSTEIN("Liechtenstein", "li"),
	LITUANIE("Lituanie", "lt"),
	LUXEMBOURG("Luxembourg", "lu"),
	MACEDOINE("Macédoine", "mk"),
	MADAGASCAR("Madagascar", "mg"),
	MALAISIE("Malaisie", "my"),
	MALDIVES("Maldives", "mv"),
	MALI("Mali", "ml"),
	MALTE("Malte", "mt"),
	MAROC("Maroc", "ma"),
	MAURICE("Maurice", "mu"),
	MAURITANIE("Mauritanie", "mr"),
	MEXIQUE("Mexique", "mx"),
	MOLDAVIE("Moldavie", "md"),
	MONACO("Monaco", "mc"),
	MONGOLIE("Mongolie", "mn"),
	MONTENEGRO("Monténégro", "me"),
	MOZAMBIQUE("Mozambique", "mz"),
	NAMIBIE("Namibie", "na"),
	NAURU("Nauru", "nr"),
	NEPAL("Népal", "np"),
	NICARAGUA("Nicaragua", "ni"),
	NIGER("Niger", "ne"),
	NIGERIA("Nigeria", "ng"),
	NOUVELLE_ZELANDE("Nouvelle-Zélande", "nz"),
	OMAN("Oman", "om"),
	OUGANDA("Ouganda", "ug"),
	OUZBEKISTAN("Ouzbékistan", "uz"),
	PAKISTAN("Pakistan", "pk"),
	PALESTINE("Palestine", "ps"),
	PALAOS("Palaos", "pw"),
	PANAMA("Panama", "pa"),
	PAPUA_NOUVELLE_GUINEE("Papouasie-Nouvelle-Guinée", "pg"),
	PARAGUAY("Paraguay", "py"),
	PAYS_BAS("Pays-Bas", "nl"),
	PEROU("Pérou", "pe"),
	PHILIPPINES("Philippines", "ph"),
	POLOGNE("Pologne", "pl"),
	PORTUGAL("Portugal", "pt"),
	QATAR("Qatar", "qa"),
	REPUBLIQUE_CENTRAFRICAINE("République centrafricaine", "cf"),
	REPUBLIQUE_DEMOCRATIQUE_DU_CONGO("République démocratique du Congo", "cd"),
	REPUBLIQUE_DU_CONGO("République du Congo", "cg"),
	REPUBLIQUE_TCHEQUE("République tchèque", "cz"),
	ROUMANIE("Roumanie", "ro"),
	ROYAUME_UNI("Royaume-Uni", "gb"),
	RUSSIE("Russie", "ru"),
	RWANDA("Rwanda", "rw"),
	SAINT_KITTS_ET_NEVIS("Saint-Kitts-et-Nevis", "kn"),
	SAINTE_LUCIE("Sainte-Lucie", "lc"),
	SAINT_MARIN("Saint-Marin", "sm"),
	SAINT_SIEGE("Saint-Siège", "va"),
	SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines", "vc"),
	SAMOA("Samoa", "ws"),
	SAO_TOME_ET_PRINCIPE("Sao Tomé-et-Principe", "st"),
	SENEGAL("Sénégal", "sn"),
	SERBIE("Serbie", "rs"),
	SEYCHELLES("Seychelles", "sc"),
	SIERRA_LEONE("Sierra Leone", "sl"),
	SINGAPOUR("Singapour", "sg"),
	SLOVAQUIE("Slovaquie", "sk"),
	SLOVENIE("Slovénie", "si"),
	SOUDAN("Soudan", "sd"),
	SRI_LANKA("Sri Lanka", "lk"),
	SUEDE("Suède", "se"),
	SUISSE("Suisse", "ch"),
	SURINAME("Suriname", "sr"),
	SWAZILAND("Swaziland", "sz"),
	SYRIE("Syrie", "sy"),
	TADJIKISTAN("Tadjikistan", "tj"),
	TAIWAN("Taïwan", "tw"),
	TANZANIE("Tanzanie", "tz"),
	TCHAD("Tchad", "td"),
	THAILANDE("Thaïlande", "th"),
	TIMOR_ORIENTAL("Timor oriental", "tl"),
	TOGO("Togo", "tg"),
	TONGA("Tonga", "to"),
	TRINITE_ET_TOBAGO("Trinité-et-Tobago", "tt"),
	TUNISIE("Tunisie", "tn"),
	TURKMENISTAN("Turkménistan", "tm"),
	TURQUIE("Turquie", "tr"),
	TUVALU("Tuvalu", "tv"),
	UKRAINE("Ukraine", "ua"),
	URUGUAY("Uruguay", "uy"),
	VANUATU("Vanuatu", "vu"),
	VATICAN("Vatican", "va"),
	VENEZUELA("Venezuela", "ve"),
	VIETNAM("Viêt Nam", "vn"),
	YEMEN("Yémen", "ye"),
	ZAMBIE("Zambie", "zm"),
	ZIMBABWE("Zimbabwe", "zw");

	private String nom;
	private String code;

	private Pays(String nom, String code) {
		this.nom = nom;
		this.code = code;
	}

	public String toString() {
		return nom;
	}

	public String getNom() {
		return nom;
	}

	public String getCode() {
		return code;
	}

	public static Pays trouverPaysParNom(String nom) {
		for (Pays pays : values()) {
			if (pays.getNom().equalsIgnoreCase(nom)) {
				return pays;
			}
		}
		return null; // Si aucun pays n'est trouvé
	}
}
